

version: 2.1

orbs:
    heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb
    codecov: codecov/codecov@1.2.0
    node: circleci/node@4.4.0

jobs:
  run-app-test:
    docker:
      - image: circleci/ruby:2.4-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - image: circleci/postgres:9.4.12-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/what-can-you-make
    steps:
      - checkout
      # Bundle install dependencies
      - run: yarn
      - run: build
      - run: yarn test
      - codecov/upload:
          file:  ./coverage/clover.xml
      - run: rm -R node_modules
      # Database setup
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version

workflows:
  heroku_deploy:
    jobs:
      - install-node
      - run-app-test:
          requires:
            - install-node
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - run-app-test
          pre-steps:
            - run: yarn test
            - codecov/upload:
                file:  ./coverage/clover.xml
            - run: rm -R node_modules
          filters:
            branches:
              only: extra-credit