
version: '2.1'
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.4.0
  codecov: codecov/codecov@1.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  test_my_app:
    jobs:
      - test
            