
version: '2.1'
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.4.0
  codecov: codecov/codecov@1.2.0

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
workflows:
  test_my_app:
    jobs:
      - install-node-example
      - node/test
            